version: "3.7"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: wordpress-php
    expose:
      - 9000
      - 9001
    depends_on:
      - db
    volumes:
      - ./wordpress:/code:z
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: wordpress-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - php
    volumes:
      - ./wordpress:/code:z
  db:
    image: mysql:8.0
    container_name: wordpress-db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql:z
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
