version: '3.3'
services:
  php:
    build: ./Docker/php
    volumes:
      - ./wordpress:/code
    expose:
      - '9000'
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./wordpress:/code
      - ./Docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./Docker/nginx/logs:/var/log/nginx
    links:
      - php
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes: 
      - ./Docker/db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'wordpress'
