version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: wordpress_web
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html:cached,z
      # - ./wordpress/wp-content/themes/<YOUR_THEME_FOLDER>:/var/www/html/wp-content/themes/<YOUR_THEME_FOLDER>:delegated,z

  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql:cached,z
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'wordpress'

volumes:
  database:
